---
- name: Setup Kubernetes
  hosts: all
  become: yes
  tasks:
    - name: Install dependencies
      import_tasks: tasks/dependencies.yml
    - name: configure and startup services
      import_tasks: tasks/startup.yml
...
