---
- name: Setup Kubernetes
  hosts: all
  become: yes
  tasks:
    - name: Install dependencies
      import_tasks: tasks/dependencies.yml
    - name: start systemd units
      import_tasks: tasks/config.yml
...
