---
- name: Install Kubernetes repo
  ansible.builtin.copy:
    src: files/kubernetes.repo
    dest: /etc/yum.repos.d/kubernetes.repo

- name: Install CRI-O repo
  ansible.builtin.copy:
    src: files/cri-o.repo
    dest: /etc/yum.repos.d/cri-o.repo

- name: Install CRI-O
  ansible.builtin.package:
    name: cri-o
    state: present

- name: install kubelet
  ansible.builtin.package:
    name: kubelet
    state: present

- name: install kubeadm
  ansible.builtin.package:
    name: kubeadm
    state: present

- name: install kubectl
  ansible.builtin.package:
    name: kubectl
    state: present

...
