---
- name: setup crio
  block:
    - name: make systemd cgroup_manager
      ansible.builtin.copy:
        src: files/conf/crio/11-ansible.conf
        dest: /etc/crio/crio.conf.d/11-ansible.conf

    - name: start crio
      ansible.builtin.service:
        name: crio
        enabled: true
        state: started

- name: setup control plane
  block:
    - name: Disable swap memory
      ansible.builtin.command:
        argv:
          - swapoff
          - -a

    - name: enable ip_forward
      ansible.posix.sysctl:
        sysctl_file: /etc/sysctl.d/k8s.conf
        name: net.ipv4.ip_forward
        value: 1
        state: present

    - name: setup control plane
      ansible.builtin.command:
        argv:
          - kubeadm
          - init
          - --pod-network-cidr=10.85.0.0/16
          - --cri-socket=unix:///var/run/crio/crio.sock

    - name: fetch kubeconfig
      ansible.builtin.fetch:
        src: /etc/kubernetes/admin.conf
        dest: ~/.kube/config-vagrant
...
